### PR TITLE
added progress bar

### PR DESCRIPTION
**Pull request by viggo-w**
Added a progress bar that shows the search progress. It works great on Linux idk about Windows

How it looks:

https://user-images.githubusercontent.com/53278263/210619792-eca1f88d-0fa9-464f-aea4-ddf71c77f601.mp4

### CODE REVIEW

**Review by SerjSX — APPROVED** [review]
All good, thanks. Will approve merge and then I will do some modifications myself on it.

**Comment by SerjSX** [comment]
Check out the tweaks I did after merging and lmk if all runs well

**Comment by viggo-w** [comment]
> Check out the tweaks I did after merging and lmk if all runs well

Everything works great

**Comment by SerjSX** [comment]
> > Check out the tweaks I did after merging and lmk if all runs well
> 
> Everything works great

Perfect. I implemented a new section next to Collections named APIs (not yet on Github) and added searching with https://pypi.org/project/RarbgAPI/ will push it as a release after further testing. Only downside is that the API is only giving the torrent link, the normal site link is returning None, so it will directly open torrent client. Will update the README after adding it

**Comment by viggo-w** [comment]
> Only downside is that the API is only giving the torrent link, the normal site link is returning None, so it will directly open torrent client.

To me that sounds like a good thing. Especially for users that does not use an ad blocker

**Comment by SerjSX** [comment]
> > Only downside is that the API is only giving the torrent link, the normal site link is returning None, so it will directly open torrent client.
> 
> To me that sounds like a good thing. Especially for users that does not use an ad blocker

Yeah it is, just that I was goaling more on searching, but with APIs like these they make it easier so yeah why not. If there are more APIs like these I'll def look into them.

Looks like the API is a bit outdated so hopefully it doesn't fail in the future

**Comment by viggo-w** [comment]
Another question: what is the point of extracting Beautiful Soup and CustomTkinter from .zip files when you can just install them with pip?

**Comment by SerjSX** [comment]
> Another question: what is the point of extracting Beautiful Soup and CustomTkinter from .zip files when you can just install them with pip?

They both look for files to run properly and the folders are needed to be there, it is annoying but 🤷‍♂️ or else the program would throw errors, for example customtkinter looks for a json file for the default theme.

**Pull request merged**
